[package]
name = "pomodoro"
version = "0.1.0"
authors = ["Naman Manchanda <namanm1@icloud.com>"]
edition = "2021"

[dependencies]
rodio = "0.20.1"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"